cleanup_grib: true
download:
  cycle: '2024-01-01T00:00:00'
  destination_bucket: oceanum-data-dev
  destination_prefix: nwp-data/
  max_lead_time: 6
  overwrite: false
  product: gfs
  resolution: 0p25
  source_bucket: global-forecast-system

# Multiple process configurations - all run on the same downloaded GRIB files
# grib_path will be automatically set to the download location
process:
  # Process 1: Extract 10m winds
  - chunks: null
    filter_by_keys:
      typeOfLevel: heightAboveGround
      level: 10
    grib_path: /tmp/nwp-data/gfs/0p25/20240101/00/  # Will be overridden if download runs
    output_path: gs://oceanum-data-dev/forecast/gfs_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
    overwrite: false
    write_local_first: true
    local_temp_dir: null
    max_upload_workers: 16
    variables:
      - u10
      - v10

  # Process 2: Extract 2m temperature and humidity  
  - chunks: null
    filter_by_keys:
      typeOfLevel: heightAboveGround
      level: 2
    grib_path: /tmp/nwp-data/gfs/0p25/20240101/00/  # Will be overridden if download runs
    output_path: gs://oceanum-data-dev/forecast/gfs_0p25_surface_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
    overwrite: false
    write_local_first: true
    local_temp_dir: null
    max_upload_workers: 16
    variables:
      - t2m
      - d2m
