cleanup_grib: false

download:
  destination_bucket: null
  local_download_dir: /tmp/nwp-data
  max_lead_time: 7
  overwrite: false
  product: ecmwf-hres
  resolution: 0p25
  source_bucket: ecmwf-forecasts
  validate_before_download: true

process:
  - filter_by_keys: {typeOfLevel: heightAboveGround, level: 10}
    # grib_path: /tmp/nwp-data/ecmwf/hres/0p25/{cycle:%Y%m%d}/{cycle:%H}/
    zarr_path: gs://oceanum-data-dev/forecast/ecmwf_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
    max_grib_workers: 8
    clean_coords: true
    variables: [u10, v10]
    chunks: {time: -1, longitude: 128, latitude: 128}
    max_upload_workers: 8
    upload_timeout: 600
    upload_max_retries: 3
    verify_upload: true
  # - filter_by_keys: {typeOfLevel: meanSea}
  #   zarr_path: gs://oceanum-data-dev/forecast/msl_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
  #   max_grib_workers: 8
  #   clean_coords: true
  #   variables: [msl]
  #   chunks: {time: -1, longitude: 128, latitude: 128}
  #   max_upload_workers: 8
  #   upload_timeout: 600
  #   upload_max_retries: 3
  #   verify_upload: true
  # - filter_by_keys: {typeOfLevel: surface}
  #   zarr_path: gs://oceanum-data-dev/forecast/tp_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
  #   max_grib_workers: 8
  #   clean_coords: true
  #   variables: [tp]
  #   chunks: {time: -1, longitude: 128, latitude: 128}
  #   max_upload_workers: 8
  #   upload_timeout: 600
  #   upload_max_retries: 3
  #   verify_upload: true
  # - filter_by_keys: {typeOfLevel: surface}
  #   zarr_path: gs://oceanum-data-dev/forecast/tprate_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
  #   max_grib_workers: 8
  #   clean_coords: true
  #   variables: [tprate]
  #   chunks: {time: -1, longitude: 128, latitude: 128}
  #   max_upload_workers: 8
  #   upload_timeout: 600
  #   upload_max_retries: 3
  #   verify_upload: true