# Example GFS Download Configuration
# Downloads GFS 0.25° forecast data and creates Zarr archives
# 
# This config has a default cycle for testing.
# For production, use config-production.yaml which requires cycle via CLI/env.

cleanup_grib: false  # Keep GRIB files after processing

download:
  cycle: '2025-10-15T00:00:00'  # Default for testing (override with --cycle or $CYCLE)
  destination_bucket: null  # Download to local disk
  local_download_dir: /tmp/nwp-data
  max_lead_time: 3  # Short lead time for testing
  overwrite: false
  product: gfs
  resolution: 0p25
  source_bucket: global-forecast-system
  
  # File availability validation (recommended for production)
  validate_before_download: true  # Fail fast if files not ready

process:
  # Wind 10m (u10 + v10)
  - filter_by_keys:
      typeOfLevel: heightAboveGround
      level: 10
    grib_path: /tmp/nwp-data/gfs/0p25/{cycle:%Y%m%d}/{cycle:%H}/
    output_path: gs://oceanum-data-dev/forecast/gfs_0p25_wind10m_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
    overwrite: true  # Delete existing Zarr before uploading new one
    write_local_first: true  # Write to local temp, then upload
    local_temp_dir: null  # Use system temp dir
    max_upload_workers: 8  # Parallel uploads (adjust based on available CPU)
    chunks:
      time: -1
      longitude: 128
      latitude: 128
    variables:
      - u10
      - v10

  # Sea ice concentration (siconc)
  - filter_by_keys:
      typeOfLevel: surface
      stepType: instant  # Required to disambiguate surface variables
    grib_path: /tmp/nwp-data/gfs/0p25/{cycle:%Y%m%d}/{cycle:%H}/
    output_path: gs://oceanum-data-dev/forecast/gfs_0p25_icec_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
    overwrite: true  # Delete existing Zarr before uploading new one
    write_local_first: true  # Write to local temp, then upload
    local_temp_dir: null  # Use system temp dir
    max_upload_workers: 8  # Parallel uploads (adjust based on available CPU)
    chunks:
      time: -1
      longitude: 128
      latitude: 128
    variables:
      - siconc  # Sea ice concentration (0-1)
