# Example configuration for NWP Download workflow

download:
  # Product selection: gfs, ecmwf-hres, or ecmwf-ens
  product: gfs
  
  # Resolution: 0p25 (0.25°), 0p50 (0.5°), 1p00 (1.0°)
  resolution: 0p25
  
  # Forecast initialization time/cycle (ISO format)
  # Hour must be 0, 6, 12, or 18 (for ECMWF only 0 or 12)
  # Examples: "2024-01-01T00:00:00" for 00z cycle
  #           "2024-01-01T06:00:00" for 06z cycle
  cycle: "2024-01-01T00:00:00"
  
  # Maximum lead time in hours
  max_lead_time: 120
  
  # Source GCS bucket (public archive)
  source_bucket: gcp-public-data-arco-era5
  
  # Destination GCS bucket (your bucket)
  destination_bucket: your-bucket-name
  
  # Optional prefix for destination paths
  destination_prefix: nwp-data/
  
  # Overwrite existing files
  overwrite: false

process:
  # Path to GRIB files (output from download step)
  grib_path: gs://your-bucket-name/nwp-data/gfs/0p25/20240101/00/
  
  # Variables to extract from GRIB files
  # Common variables:
  #   - t2m: 2-meter temperature
  #   - u10, v10: 10-meter wind components
  #   - tp: Total precipitation
  #   - msl: Mean sea level pressure
  #   - sp: Surface pressure
  variables:
    - t2m
    - u10
    - v10
    - tp
  
  # Output Zarr archive path
  # Supports Python datetime formatting with {cycle:format} syntax:
  # Examples:
  #   - gs://bucket/gfs_{cycle:%Y%m%d}_{cycle:%Hz}.zarr  -> gfs_20240101_00z.zarr
  #   - gs://bucket/gfs_{cycle:%Y-%m-%d_%H%M}.zarr       -> gfs_2024-01-01_0000.zarr
  #   - gs://bucket/gfs_{cycle:%Y%m%d%H}.zarr            -> gfs_2024010100.zarr
  # 
  # Legacy placeholders also supported: {date}, {time}, {timestamp}, {cycle}
  zarr_path: gs://your-bucket-name/output/forecast_{cycle:%Y%m%d}_{cycle:%Hz}.zarr
  
  # Optional: Custom timestamp format (default: %Y%m%d_%H%M%S)
  # timestamp_format: "%Y%m%d_%H%M%S"
  
  # Optional: Filter GRIB messages by keys
  # filter_by_keys:
  #   typeOfLevel: surface
  
  # Optional: Chunking specification for Zarr
  # chunks:
  #   time: 1
  #   latitude: 100
  #   longitude: 100
  
  # Overwrite existing Zarr archive
  overwrite: false
  
  # Write to local temp directory first, then upload to GCS
  # Helps avoid network issues when writing large Zarr archives
  write_local_first: false
  
  # Optional: Custom local temp directory (default: system temp)
  # local_temp_dir: /tmp/zarr-temp

# Cleanup GRIB files after processing
cleanup_grib: false
